### ISSUE TITLE
Column names switched in return value of `simulate_chains`

### ISSUE THREAD

**Issue by sbfnk** [epiverse-trace/epichains#238]
Please place an "x" in all the boxes that apply
---------------------------------------------
  
- [X] I have the most recent version of epichains and R
- [X] I have found a bug
- [X] I have a [reproducible example](http://reprex.tidyverse.org/articles/reprex-dos-and-donts.html)

--------
  
I think the `infectee_id` and `sim_id` columns are swapped in the return value of `simulate_chains`. The first column below is the simulation (or index case) running form 1 to 3. The second one is the ID fo the infectee within each simulation.

I also wonder, in line with the terminology used in the documentation (and argument names) whether it would be clearer if the `sim_id` column was renamed to `index_case`.

``` r
library("epichains")

set.seed(1)
chains_pois_offspring <- simulate_chains(
  index_cases = 3,
  statistic = "size",
  offspring_dist = rpois,
  stat_max = 10,
  lambda = 1
)
chains_pois_offspring |>
as.data.frame()
#>    infectee_id sim_id infector_id generation
#> 1            1      1          NA          1
#> 2            2      1          NA          1
#> 3            3      1          NA          1
#> 4            2      2           1          2
#> 5            3      2           1          2
#> 6            2      3           2          3
#> 7            2      4           2          3
#> 8            2      5           3          4
#> 9            2      6           3          4
#> 10           2      7           4          4
#> 11           2      8           4          4
#> 12           2      9           4          4
#> 13           2     10           5          5
#> 14           2     11           6          5
```

<sup>Created on 2024-03-26 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>
---------

**Comment by jamesmbaazam** [comment]
Thanks for picking this up @sbfnk. This issue is related to #175, so I'll address them jointly. The suggestions for column name changes in the two issues are slightly contradictory but I agree that it would make more sense to make the following changes:
- `infectee_id` -> `index_case`
- `sim_id` -> `infectee`
- `infector_id` -> `infector`

I'll remove the `_id` suffix as it's redundant. This will also prepare {epichains} for the suggestion in {simulist} to align outputs: https://github.com/epiverse-trace/simulist/issues/43#issuecomment-2085576932.
