### ISSUE TITLE
Version number

### ISSUE THREAD

**Issue by jamesmbaazam** [epiverse-trace/epichains#32]
I am considering "resetting" the version number to 0.0.0.9999, since the package is basically in its initial dev state now. This would mean that in terms of sorting, this new version number might still be the latest. I think it presents another interesting question in the development of this package.

@sbfnk @Bisaloo Any thoughts on this?

**Comment by Bisaloo** [comment]
It seems to me that continuing the version number progression is slightly more conservative and makes it clear that this package is a fork. 
Some people also use the version number as some kind of proxy of how much hindsight you have collected in this package. Since epichains is going to benefit from lessons learned in bpmodels, it probably makes sense to keep it.

Which drives me to ask: can we flip the question? Which benefits do you see to resetting the version number?

**Comment by jamesmbaazam** [comment]
> Which drives me to ask: can we flip the question? Which benefits do you see to resetting the version number?

The most obvious benefit is clear communication with potential users and developers. That is, a package with that semantic version is highly unstable (function names and arguments could change, the interface could change, etc). Such a package is used at the user's risk. It can be tried but should not be embedded into pipelines or used as a dependency yet as things might change without much warning. The current version of 0.2.xyz promises some kind of maturity/stability that might not be true.

**Comment by jamesmbaazam** [comment]
I have decided to revert it to v0.1.0 here (). The NEWS file () will explain the name change and rationale.

**Comment by jamesmbaazam** [comment]
Closing this as fixed in #33.
